app:
  ip: "127.0.0.1"
  env:  "development"
  port: 3334
  debug: true

mongodb:
  connection: "mongodb://superadmin:123456@51.79.184.185:27017/"
  database: "developments"  

appAuth : 
  tokenSecret: "secret"

googleAuth:
  googleAuthUrl: "https://www.googleapis.com/oauth2/v2/userinfo?access_token="
  redirectURL: "http://localhost:3334/apix/v1/google_auth/callback" 
  clientID: "781374464096-1gdncta7qoh9atlpf07sb4gfonq04lci.apps.googleusercontent.com"
  clientSecret: "GaXVKMIHTuT-dNTkEBMym-36"
  scopes: "https://www.googleapis.com/auth/userinfo.email"
  authStateString: "pseudo-random"

s3:
  bucketName: "bidna-project"
  region: "ap-southeast-1"
  accessKeyId: "AKIA3IA7PUU6BPWB44VS"
  accessSecretKey: "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"  